services:
  llm_orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talos_orchestrator_plane
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: python main.py
